# -*- coding: utf-8 -*-
"""MB-CBSOT-Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwgV8xIGh3A4na5jwmwR3rxHy-9JwRtS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/drive/MyDrive/cbsot ml/Telco_customer_churn.xlsx")

df

df.shape

df.info()

df['Churn Label'].value_counts()

plt.figure(figsize=(8,5))
sns.histplot(df['Tenure Months'], bins = 30, kde = True)
plt.xlabel('Tenure Months')
plt.ylabel('Customer Count')
plt.title('Distribution of Tenure Months vs No. of Customers')
plt.show()

df['Tenure Months'].max()

df['Tenure Months'].min()

df.info()

plt.figure(figsize=(8,5))
sns.boxplot(x = 'Churn Label', y = 'Tenure Months', data = df )
plt.xlabel('Tenure Months')
plt.ylabel('Customer Count')
plt.title('Churn v/s Tenure Months')
plt.show()

df['Churn Label'].unique()

df[df['Churn Label'] == 'Yes']

plt.figure(figsize=(8,5))
sns.histplot(x = 'Monthly Charges', y = 'Tenure Months', data = df )
plt.xlabel('Month Charges')
plt.ylabel('Customer Count')
plt.title('Churn v/s Tenure Months')
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Monthly Charges'], bins = 30, kde = True)
plt.xlabel('Month Charges')
plt.ylabel('Customer Count')
plt.title('Monthly Charges vs No. of Customers')
plt.show()

df['Monthly Charges'].max()

df['Monthly Charges'].min()

plt.figure(figsize=(8,5))
sns.boxplot(x = 'Churn Label', y = 'Monthly Charges', data = df )
plt.xlabel('Churn Label')
plt.ylabel('Monthly charges')
plt.title('Churn v/s Monthly Charges')
plt.show()

df[df['Churn Label'] == 'Yes']['Monthly Charges'].quantile([0.25, 0.5, 0.75])

df[df['Churn Label'] == 'No']['Monthly Charges'].quantile([0.25, 0.5, 0.75])

df['Monthly Charges'].describe()

df['Monthly Charges'].quantile([0.25, 0.5, 0.75])

df['Contract'].unique()

df['Contract'].value_counts

df['Contract'].value_counts()

plt.figure(figsize=(8,5))
sns.countplot(x = 'Contract', hue = 'Churn Label', data = df )
plt.xlabel('Contract')
plt.ylabel('count')
plt.title('Contract v/s Count')
plt.show()

df.info()

df['Internet Service'].unique()

plt.figure(figsize=(8,5))
sns.countplot(x = 'Internet Service', hue = 'Churn Label', data = df )
plt.xlabel('Internet Service')
plt.ylabel('count')
plt.title('Internet Service v/s Count')
plt.show()

df['Payment Method'].unique()

plt.figure(figsize=(10,5))
sns.countplot(x = 'Payment Method', hue = 'Churn Label', data = df )
plt.xlabel('Payment Method')
plt.ylabel('count')
plt.title('Payment Method v/s Count')
plt.show()

df['Tech Support'].unique()

plt.figure(figsize=(8,5))
sns.countplot(x = 'Tech Support', hue = 'Churn Label', data = df )
plt.xlabel('Tech Support')
plt.ylabel('count')
plt.title('Tech Support v/s Count')
plt.show()

avg_tenure = df.groupby("Churn Label")['Tenure Months'].mean()

avg_tenure

max_tenure = df.groupby("Churn Label")['Tenure Months'].max()

max_tenure

"""Data Cleaning"""

df.info()

numerical_cols=['Tenure Months', 'Monthly Charges', 'Churn Value', 'Churn Score', 'CLTV']
corrleation_matrix = df[numerical_cols].corr()

corrleation_matrix

contract_churn = pd.crosstab(df['Contract'], df['Churn Label'], normalize = 'index')
contract_churn

"""# Data Cleaning

"""

df.info()

df['Total Charges']

df['Total Charges']= pd.to_numeric(df['Total Charges'], errors = 'coerce')

df.info()

df['Total Charges']

"""9 June and 10 June"""

df['Total Charges'].dtype

df['Total Charges'].isnull().sum() # Check number of Numerical Values

df[df['Total Charges'].isnull()]['Tenure Months']

df[df['Total Charges'].isnull()]['Tenure Months'].shape

df['Total Charges'] = df['Total Charges'].fillna(0)

df['Total Charges'].isnull().sum()

df.shape

df.info()

# Customer ID, Count, Country, State, City, Zip Code, Latitute Longitutde, Lat Long, --> these columns can be dropped, little to no significance for our problem statement on customer retention.

"""# Customer ID, Count, Country, State, City, Zip Code, Latitute Longitutde, Lat Long, --> these columns can be dropped, little to no significance for our problem statement on customer retention.

# Churn Label, Churn Score, CLTV, Churn Reason also to be dropped as these columns will lead to Data Leakage. Model will accidentally get info abt the answer.
"""

df.info()

df.shape

drop_columns = ['CustomerID', 'Count', 'Country', 'State', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Churn Label', 'Churn Reason', 'Churn Score', 'CLTV' ]

df = df.drop(columns = drop_columns)

df.info()

df.shape

df_encoded = pd.get_dummies(df, drop_first = True)

df_encoded.head() # top 5 rows

df['City'].unique()

df['City'].unique()
df['City'].value_counts()

df_encoded.shape

df = df.drop(columns=['City'])

df.shape

df.info()

df_encoded = pd.get_dummies(df, drop_first= True)

df_encoded.shape #ONE-HOT ENCODING

df_encoded

X = df_encoded.drop(columns = ['Churn Value'])
Y = df_encoded['Churn Value']

X = df_encoded.drop('Churn Value', axis = 1)
Y = df_encoded['Churn Value']

X.shape
Y.shape

print(X)

print(Y)

"""# Machine Learning Part Implementation"""

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.20, random_state=42)

X_train.shape

X_test.shape

Y_train.shape

Y_test.shape

"""# 12 June"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators = 100, random_state = 42)

rf_model.fit(X_train, Y_train)

y_pred=rf_model.predict(X_test)

Y_test

y_pred

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred)

print(cm)

from sklearn.metrics import classification_report

print(classification_report(Y_test, y_pred))

"""**Approach 1 - Handle Class Imbalance**"""

rf_balanced = RandomForestClassifier(n_estimators = 100, random_state = 42, class_weight = 'balanced')
rf_balanced.fit(X_train, Y_train)
y_pred_balanced = rf_balanced.predict(X_test)
accuracy_balanced = accuracy_score(Y_test, y_pred_balanced)
cm_balanced = confusion_matrix(Y_test, y_pred_balanced)
print(accuracy_balanced, cm_balanced)
print(classification_report(Y_test, y_pred_balanced))

"""**Approach 2 - Hyperparameter Tuning**"""

rf_tuned = RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')
rf_tuned.fit(X_train, Y_train)
y_pred_tuned = rf_tuned.predict(X_test)
print(classification_report(Y_test, y_pred_tuned))

"""### to optimize this"""

rf_tuned2 = RandomForestClassifier(n_estimators=150,max_depth=20,random_state=42,class_weight='balanced')
rf_tuned2.fit(X_train, Y_train)
y_pred_tuned2 = rf_tuned2.predict(X_test)
print(classification_report(Y_test, y_pred_tuned2))

"""# Approach 3 Feature Importance Analysis"""

import pandas as pd
feature_importance = pd.DataFrame({
    'Features': X.columns,
    'Importance': rf_tuned.feature_importances_})
feature_importance = feature_importance.sort_values(by='Importance', ascending=False)
print(feature_importance)

print(feature_importance .tail(15))

X_selected = X.drop(['Phone Service_Yes', 'Multiple Lines_No phone service'], axis=1)

X_train_sel, X_test_sel, Y_train_sel, Y_test_sel = train_test_split(X_selected,Y,test_size=0.2,random_state=42)

rf_selected = RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')
rf_selected.fit(X_train_sel, Y_train_sel)
y_pred_selected = rf_selected.predict(X_test_sel)
print(classification_report(Y_test_sel, y_pred_selected))

"""# Approach Combination of trees and depth"""

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

n_estimators_list = [100, 200, 300, 400, 500]
max_depth_list = [5, 10, 15, 20]

results = []

for n_trees in n_estimators_list:
    for depth in max_depth_list:
        rf = RandomForestClassifier(n_estimators=n_trees,max_depth=depth,random_state=42,class_weight='balanced')
        rf.fit(X_train, Y_train)
        y_pred = rf.predict(X_test)
        accuracy = accuracy_score(Y_test, y_pred)
        recall = recall_score(Y_test, y_pred)
        precision = precision_score(Y_test, y_pred)
        f1 = f1_score(Y_test, y_pred)
        results.append({'Trees': n_trees, 'Max Depth': depth, 'Accuracy': accuracy, 'Recall': recall, 'Precision': precision, 'F1 Score': f1})

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by=['Recall', 'Accuracy'], ascending=False)
print(results_df.head(20))
print(results_df)

from sklearn.model_selection import cross_val_score
final_rf =  RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42,class_weight='balanced')
# final_rf.fit(X_train, Y_train)
# y_pred = final_rf.predict(X_test)

cv_accuracy = cross_val_score(final_rf, X, Y, cv=5, scoring = 'accuracy')

cv_accuracy

cv_accuracy.mean()

cv_recall = cross_val_score(final_rf, X, Y, cv=5, scoring = 'recall')

cv_recall

cv_recall.mean()

"""###17 June

# Optional
"""

from sklearn.metrics import roc_auc_score, roc_curve

import matplotlib.pyplot as plt

y_prob = rf_tuned.predict_proba(X)

y_prob1 = rf_tuned.predict_proba(X_test)

churn_probability = y_prob[:, 1]

churn_prob = y_prob1[:, 1]

fpr, tpr, threshold = roc_curve(Y_test, churn_prob)
auc_score = roc_auc_score(Y_test, churn_prob)
print(auc_score)

"""# Customer Segmentation"""

segmentation_data = pd.DataFrame({
    'Tenure Months': X['Tenure Months'],
    'Monthly Charges': X['Monthly Charges'],
    'Total Charges': X['Total Charges'],
    'Churn Probability': churn_probability
})

segmentation_data

"""# Implementation of K-means"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(segmentation_data)

print(scaled_data[:5])

from sklearn.cluster import KMeans

wcss = []

for k in range(1, 16):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8, 6))
plt.plot(range(1, 16), wcss, marker='o')
plt.xlabel("Number of Clusters k")
plt.ylabel("WCSS")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)

clusters = kmeans.fit_predict(scaled_data)

segmentation_data['Cluster'] = clusters

segmentation_data

print(segmentation_data.head())

cluster_summary = segmentation_data.groupby('Cluster').mean()

print(cluster_summary)

cluster_names = {
    0: 'Budget Loyal Customers',
    1: 'High Risk New Customers',
    2: 'Loyal Premium Customers'
}

segmentation_data['Cluster Segment'] = segmentation_data['Cluster'].map(cluster_names)

segmentation_data

segmentation_data[['Cluster', 'Cluster Segment']]

segmentation_data[['Cluster', 'Cluster Segment']].head()

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='Tenure Months',
    y='Monthly Charges',
    hue='Cluster Segment',
    data=segmentation_data,
    palette='viridis'
)

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='Tenure Months',
    y='Monthly Charges',
    hue='Cluster Segment',
    data=segmentation_data,
    palette='Spectral'
)

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='Tenure Months',
    y='Churn Probability',
    hue='Cluster Segment',
    data=segmentation_data,
    palette='Spectral'
)

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='Monthly Charges',
    y='Churn Probability',
    hue='Cluster Segment',
    data=segmentation_data,
    palette='Spectral'
)

plt.figure(figsize=(8, 6))

sns.scatterplot(
    x='Total Charges',
    y='Churn Probability',
    hue='Cluster Segment',
    data=segmentation_data,
    palette='Spectral'
)